spring:
  application:
    name: cricketclub-rest-api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}?autoReconnect=true
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true

info:
  component: This is REST API for Wembley Cricket Club.

server:
  port: 8001
  contextPath: /api/

hystrix:
  streamEnabled: true
  enabled: true

archaius:
  dynamicPropertyFactory:
    registerConfigWithJMX: true

endpoints:
    restart:
      enabled: true

oauth:
  resourceId: service-service
  clientId: 4f7ec648a48b9d3fa239b497f7b6b4d8019697bd
  clientSecret: edfeba07ec1dd4ff45928ee715a8e1ecc149a060
  tokenEndpoint: http://${oauth.hostname}:8080/oauth/check_token
  authzEndpoint: http://${oauth.hostname}:8080/uaa/oauth/authorize

logging:
   levels:
     org.springframework.boot.env.PropertySourcesLoader: TRACE
     org.springframework.web: DEBUG
